server.port: 9005
spring:
  application:
    name: large-scale-system-article-read-service
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: large-scale-system-article-read-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

endpoints:
  large-scale-system-article-service:
    url: http://127.0.0.1:9000
  large-scale-system-comment-service:
    url: http://127.0.0.1:9001
  large-scale-system-like-service:
    url: http://127.0.0.1:9002
  large-scale-system-view-service:
    url: http://127.0.0.1:9003

